# Generated by Django 4.2.24 on 2025-09-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="dtNasc",
            field=models.DateField(
                help_text="Nascimento no formato AAAA-MM-DD",
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(help_text="Entre o logradouro", max_length=200),
                ),
                (
                    "cidade",
                    models.CharField(help_text="Entre a cidade", max_length=100),
                ),
                (
                    "estado",
                    models.CharField(help_text="Entre o estado", max_length=100),
                ),
                ("cep", models.CharField(help_text="Entre o CEP", max_length=20)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to="contatos.pessoa",
                    ),
                ),
            ],
        ),
    ]
